version: '3.1'

services:

  mongo:
    container_name: docker_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    volumes: 
      - ./data:/data/db
